#!/bin/bash

echo "selecting new kernel"
sleep 1
eselect kernel set 2
echo "going to source"
sleep 1
cd /usr/src/linux
echo "copying .config"
sleep 1
zcat /proc/config.gz > /usr/src/linux/.config &&
echo olddefconfig
sleep 1
make olddefconfig &&
echo "make && install"
sleep 1
make -j14 && make -j14 modules_install &&
make install &&
echo eclean
sleep 1
eclean-kernel -An2
echo module-rebuild
sleep 1
emerge @module-rebuild
