#!/bin/bash

echo "selecting new kernel"
sleep 1
eselect kernel set 2
echo "going to kernel source"
sleep 1
cd /usr/src/linux
# sys-kernel/gentoo-sources need to be emerged with  
# (USE=experimental) to have /proc/config.gz
echo "copying currently in-use kernel .config to new sources"
sleep 1
zcat /proc/config.gz > /usr/src/linux/.config
## Running make olddefconfig will keep all of the options from the old 
## .config and set the new options to their recommended (i.e. default)
echo "make olddefconfig"
sleep 1
make olddefconfig
echo "make && install kernel"
sleep 1
make CC=clang LD=ld.lld NM=llvm-nm AR=llvm-ar LLVM_IAS=1 -j14 &&
make CC=clang LD=ld.lld NM=llvm-nm AR=llvm-ar LLVM_IAS=1 -j14 modules_install &&
make install
echo "remove all built kernel files and build dirs; keep 2 kernels (past/current)"
sleep 1
eclean-kernel -n3
echo "rebuild kernel modules"
sleep 1
emerge @module-rebuild
