#!/bin/bash

cd /home/mrturcot/github/mplayer
svn update
# rm -rf mplayer &&
# svn checkout svn://svn.mplayerhq.hu/mplayer/trunk mplayer
while true; do
read -p "mplayer: Do you want to proceed? (y/n) " yn
case $yn in
	[yY] ) echo ok, we will proceed;
		break;;
	[nN] ) echo exiting...;
		exit;;
	* ) echo invalid response;;
esac
done
make clean
rm -rf ffmpeg
./configure &&
make -j14 &&
sudo make install
