#!/bin/bash

cd /home/mrturcot/github/mplayer
svn update
# rm -rf mplayer &&
# svn checkout svn://svn.mplayerhq.hu/mplayer/trunk mplayer
make clean
rm -rf ffmpeg
./configure &&
make -j14 &&
sudo make install
