#!/bin/bash

cd /home/mrturcot/github/openmw
git pull
while true; do
read -p "openmw: Do you want to proceed? (y/n) " yn
case $yn in
	[yY] ) echo ok, we will proceed;
		break;;
	[nN] ) echo exiting...;
		exit;;
	* ) echo invalid response;;
esac
done
rm -rf build
mkdir build && cd build
cmake ../ &&
make -j14

