#!/bin/bash

cd /home/mrturcot/github/osg
if [[ $(git remote show origin | grep 'out of date') ]]; then
while true; do
read -p "osg: Do you want to proceed? (y/n) " yn
case $yn in
	[yY] ) echo ok, we will proceed;
		break;;
	[nN] ) echo exiting...;
		exit;;
	* ) echo invalid response;;
esac
done
rm -rf build
mkdir build && cd build
cmake ../ &&
make -j12
#sudo make install
