#!/bin/bash

cd /usr/aarch64-unknown-linux-gnu
mount --bind /proc proc
mount --bind /sys sys
mount --bind /dev dev
mount --bind /dev/pts dev/pts
mount --bind /var/tmp/portage var/tmp/portage
cp --dereference /etc/resolv.conf /mnt/gentoo/etc
chroot . bin/bash --login
