#!/bin/bash

# get colors
source $HOME/scripts/colors

set -o xtrace

echo -en '\n'
cd $HOME/github/vkQuake
### update submodules
echo -e "${BIB}###### [ ${BIC}Checking For ${BIW}*PACKAGE_NAME ${BY}${UY}Updates${NC}${BIB} ] ######${NC}"
if [[ $(git pull --recurse-submodules --dry-run) == "Fetching" ]]
then
   echo -e "${BIB}###### [ ${BIG}${UG}Updating${NC}${BIB} ] ######${NC}"
   sleep 1
   echo submodule update &&
   echo -e "${BIB}##### [ ${UP}${BIP}Done${NC}${BIB} ] #####"
else
   :
fi
### update main repo
if [[ $(git pull) == "Already up to date." ]]
then
   echo -e "${BIB}###### [ ${BIC}Up ${BIW}To ${BY}${UY}Date${NC}${BIB} ] ######${NC}"
else
   echo -e "${BIB}###### [ ${BIG}${UG}Skipping${NC}${BIB} ] ######${NC}"
   sleep 1
   echo UPGRADING &&
   echo -e "${BIB}##### [ ${UP}${BIP}Done${NC}${BIB} ] #####"
fi
echo -en '\n'

set +o xtrace