#!/bin/bash

#set -o xtrace

# get colors
source $HOME/scripts/colors

echo -en '\n'
echo -e "${BB}###### [ ${BY}!! SUPER MEGA UPDATE !!${NC}${BB} ] ######${NC}"
sleep 1

## eix-sync

while true; do
	echo -en '\n'
	echo -e "${BB}###### [ ${BIP}Sync All Repos ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "Yes or No [${BG}y${NC}/${BR}n${NC}]") " yn
	echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} Syncing${BB} ......${NC}"
	echo -en '\n'
	sleep 1
	eix-sync &&
	echo -en '\n'
	echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
	sleep 1
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
    esac
done
echo -en '\n'

## emerge --ask --verbose --update --newuse --deep @world

while true; do
	echo -e "${BB}###### [ ${BIP}Update ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "Yes or No [${BG}y${NC}/${BR}n${NC}]") " yn
	echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} Updating${BB} ......${NC}"
	echo -en '\n'
	sleep 1
	emerge-update &&
	echo -en '\n'
	echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
	sleep 1
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
	echo -en '\n';;
    esac
done
echo -en '\n'

## Run automated kernel make/build script

while true; do
	echo -e "${BB}###### [ ${BIP}Make && Install Kernel ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "Yes or No [${BG}y${NC}/${BR}n${NC}]") " yn
	echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} Building${BB} ......${NC}"
	echo -en '\n'
	sleep 1
	autokernel &&
	echo -en '\n'
	echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
	sleep 1
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
	echo -en '\n';;
    esac
done
echo -en '\n'

## emerge @smart-live-rebuild

while true; do
	echo -e "${BB}###### [ ${BIP}Smart Live Rebuild ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "Yes or No [${BG}y${NC}/${BR}n${NC}]") " yn
	echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} Rebuilding${BB} ......${NC}"
	echo -en '\n'
	sleep 1
	emerge @smart-live-rebuild &&
	echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
	sleep 1
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
	echo -en '\n';;
    esac
done
echo -en '\n'

## emerge --ask --depclean

while true; do
	echo -e "${BB}###### [ ${BIP}Clean Dependencies ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "Yes or No [${BG}y${NC}/${BR}n${NC}]") " yn
	echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} Cleaning${BB} ......${NC}"
	echo -en '\n'
	sleep 1
	emerge-depclean &&
	echo -en '\n'
	echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
		sleep 1
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
	echo -en '\n';;
    esac
done
echo -en '\n'

echo -e "${BB}###### [ ${BY}!! Finished !!${NC}${BB} ] ######${NC}"
sleep 1

#set +o xtrace
