#!/bin/bash

#set -o xtrace

# get colors
source $HOME/scripts/colors

echo -en '\n'
echo -e "${BB}###### [ ${BY}!! SUPER MEGA UPDATE !!${NC}${BB} ] ######${NC}"
echo -en '\n'

while true; do
echo -e "${BB}###### [ ${BIP}eix-sync ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "[${BG}y${NC}/${BR}n${NC}]") " yn
echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} we will proceed${BB} ......${NC}"
		echo -en '\n'
        sleep 1
        eix-sync &&
        echo -en '\n'
        echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
		echo -en '\n';;
esac
done
echo -en '\n'
while true; do
echo -e "${BB}###### [ ${BIP}full-update ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "[${BG}y${NC}/${BR}n${NC}]") " yn
echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} we will proceed${BB} ......${NC}"
		echo -en '\n'
        sleep 1
        full-update &&
        echo -en '\n'
        echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
		echo -en '\n';;
esac
done
echo -en '\n'
while true; do
echo -e "${BB}###### [ ${BIP}make & install kernel ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "[${BG}y${NC}/${BR}n${NC}]") " yn
echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} we will proceed${BB} ......${NC}"
        sleep 1
        autokernel &&
        echo -en '\n'
        echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
		echo -en '\n';;
esac
done
echo -en '\n'
while true; do
echo -e "${BB}###### [ ${BIP}smart-live-rebuild ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "[${BG}y${NC}/${BR}n${NC}]") " yn
echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} we will proceed${BB} ......${NC}"
        sleep 1
        smart-update &&
        echo -en '\n'
        echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
		echo -en '\n';;
esac
done
echo -en '\n'
while true; do
echo -e "${BB}###### [ ${BIP}depclean ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "[${BG}y${NC}/${BR}n${NC}]") " yn
echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} we will proceed${BB} ......${NC}"
        sleep 1
        clean &&
        echo -en '\n'
        echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
		echo -en '\n';;
esac
done
echo -en '\n'
echo -e "${BB}###### [ ${BY}!! FINISHED !!${NC}${BB} ] ######${NC}"
echo -en '\n'

#set +o xtrace
