#!/bin/bash

echo "go to kernel sources"
sleep 0.5
cd /usr/src/linux
echo "make && install kernel"
sleep 1
make -j14 && make -j14 modules_install &&
echo install kernel
sleep 1
make install &&
echo "update grub"
sleep 1
grub-mkconfig -o /boot/grub/grub.cfg
