#!/bin/bash

emaint sync -r mv
emaint sync -r steam-overlay
emaint sync -r guru
emaint sync -r pf4public
emaint sync -r src_prepare-overlay
emaint sync -r kde
emaint sync -r slonko
emaint sync -r menelkir
eix-update
eix-remote update
eix-diff
