#!/bin/bash

cd /home/mrturcot/servers/purpur-mc
screen -dmS purpur java -Xms10G -Xmx10G -Xmn1G -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UseCompressedOops -XX:-UsePerfData -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=2 -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=50 -XX:G1HeapRegionSize=1 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 --add-modules=jdk.incubator.vector -jar /home/mrturcot/servers/purpur-mc/purpur/build/libs/purpurclip.jar nogui
