#!/bin/bash

#set -o xtrace

# Get colors
source $HOME/scripts/colors

## vkquake

cd $HOME/github/vkquake

echo -en '\n'
echo -e "${BB}###### [ ${BIG}!! SUPER MEGA GIT UPDATE !!${NC}${BB} ] ######${NC}"
echo -en '\n'

echo -e "${BIB}###### [ ${BIC}vkQuake ${NC}${BIB}] ######${NC}"
if [[ $(git pull --dry-run) == *master* ]]; then
while true; do
	echo -e "${BB}###### [ ${BIP}update ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "Yes or No [${BG}y${NC}/${BR}n${NC}]") " yn
	echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} we will proceed${BB} ......${NC}"
	echo -en '\n'
	sleep 1
	build-vkquake &&
	echo -en '\n'
	echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB}] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
		break;;
	* )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
	echo -en '\n';;
esac
done
else
	echo -e "${BIB}###### [ ${BIY}Up to Date, Skipping${NC}${BIB} ] ######${NC}";
fi
echo -en '\n'
echo -e "${BB}###### [ ${BIG}!! FINISHED !!${NC}${BB} ] ######${NC}"

## vkquake2

cd $HOME/github/vkquake2

echo -en '\n'
echo -e "${BIB}###### [ ${BIC}vkQuake2 ${NC}${BIB} ] ######${NC}"
if [[ $(git pull --dry-run) == *master* ]]; then
while true; do
	echo -e "${BB}###### [ ${BIP}update ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "Yes or No [${BG}y${NC}/${BR}n${NC}]") " yn
	echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BY}* ${BIG}OK${NC} we will proceed${BB} ......${NC}"
	echo -en '\n'
	sleep 1
	build-vkquake2 &&
	echo -en '\n'
	echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
		break;;
	* )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
	echo -en '\n';;
    esac
done
else
	echo -e "${BIB}###### [ ${BIY}Up to Date, Skipping${NC}${BIB} ] ######${NC}";
fi

echo -en '\n'
echo -e "${BB}###### [ ${BIG}!! FINISHED !!${NC}${BB} ] ######${NC}"

#set -o xtrace

