#!/bin/bash

#set -o xtrace

source $HOME/scripts/colors
echo -en '\n'
echo -e "${BIB}###### [ ${BIY}!! SUPER MEGA UPDATE !!${NC}${BIB} ] ######${NC}"
echo -en '\n'
while true; do
echo -e "${BIB}###### [ ${BIP}PASS 1${NC}${BIB} ] ######${NC}"
read -p "$(echo -e "[${BG}Yes${NC}/${BR}No${NC}]") " yn
echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BIY}* ${BIG}OK${NC}, we will proceed${BIB} ......${NC}"
		echo -en '\n'
        sleep 1
        clang --version &&
        echo -en '\n'
        echo -e "${BIB}###### [ ${BIP}!! Done !!${NC}${BIB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BIY}*${NC} Skipping${BIB} ......${NC}"
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
		echo -en '\n';;
esac
done
echo -en '\n'
while true; do
echo -e "${BIB}###### [ ${BIP}PASS 2${NC}${BIB} ] ######${NC}"
read -p "$(echo -e "[${BG}Yes${NC}/${BR}No${NC}]") " yn
echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BIY}* ${BIG}OK${NC}, we will proceed${BIB} ......${NC}"
		echo -en '\n'
        sleep 1
        clang --version &&
        echo -en '\n'
        echo -e "${BIB}###### [ ${BIP}!! Done !!${NC}${BIB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BIY}*${NC} Skipping${BIB} ......${NC}"
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
		echo -en '\n';;
esac
done
echo -en '\n'
while true; do
echo -e "${BIB}###### [ ${BIP}PASS 3${NC}${BIB} ] ######${NC}"
read -p "$(echo -e "[${BG}Yes${NC}/${BR}No${NC}]") " yn
echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BIY}* ${BIG}OK${NC}, we will proceed${BIB} ......${NC}"
		echo -en '\n'
        sleep 1
        clang --version &&
        echo -en '\n'
        echo -e "${BIB}###### [ ${BIP}!! Done !!${NC}${BIB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BIY}*${NC} Skipping${BIB} ......${NC}"
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
		echo -en '\n';;
esac
done
echo -en '\n'
while true; do
echo -e "${BIB}###### [ ${BIP}PASS 4${NC}${BIB} ] ######${NC}"
read -p "$(echo -e "[${BG}Yes${NC}/${BR}No${NC}]") " yn
echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BIY}* ${BIG}OK${NC}, we will proceed${BIB} ......${NC}"
		echo -en '\n'
        sleep 1
        clang --version &&
        echo -en '\n'
        echo -e "${BIB}###### [ ${BIP}!! Done !!${NC}${BIB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BIY}*${NC} Skipping${BIB} ......${NC}"
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
		echo -en '\n';;
esac
done
echo -en '\n'
while true; do
echo -e "${BIB}###### [ ${BIP}PASS 5${NC}${BIB} ] ######${NC}"
read -p "$(echo -e "[${BG}Yes${NC}/${BR}No${NC}]") " yn
echo -en '\n'
case $yn in
	[yY] ) echo -e " ${BIY}* ${BIG}OK${NC}, we will proceed${BIB} ......${NC}"
		echo -en '\n'
        sleep 1
        clang --version &&
        echo -en '\n'
        echo -e "${BIB}###### [ ${BIP}!! Done !!${NC}${BIB} ] ######${NC}"
		break;;
	[nN] ) echo -e " ${BIY}*${NC} Skipping${BIB} ......${NC}"
		break;;
	 * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
		echo -en '\n';;
esac
done
echo -en '\n'
echo -e "${BIB}###### [ ${BIY}!! FINISHED !!${NC}${BIB} ] ######${NC}"
echo -en '\n'

#set +o xtrace
