#!/bin/bash

## Script to automatically check repo git status. If 'behind' then pull & build; if not SKIP...

#set -o xtrace

# Get colors
source $HOME/scripts/colors

echo -en '\n'
echo -e "${BB}###### [ ${BIG}!! SUPER MEGA GIT UPDATE !!${NC}${BB} ] ######${NC}"
echo -en '\n'

cd $HOME/github/ffmpeg
echo -e "${BIB}###### [ ${BIC}ares-emu ${NC}${BIB}] ######${NC}"
if [[ $(git fetch --dry-run | grep 'master') ]]; then
while true; do
    echo -e "${BB}###### [ ${BIP}update ???${NC}${BB} ] ######${NC}"
read -p "$(echo -e "Yes or No [${BG}y${NC}/${BR}n${NC}]") " yn
    echo -en '\n'
case $yn in
    [yY] ) echo -e " ${BY}* ${BIG}OK${NC} we will proceed${BB} ......${NC}"
    echo -en '\n'
    sleep 1
    echo "YES IT WORKS!"
    #git pull &&
    #build-ares &&
    echo -en '\n'
    echo -e "${BB}###### [ ${BIP}!! Done !!${NC}${BB}] ######${NC}"
        break;;
    [nN] ) echo -e " ${BY}*${NC} Skipping${BB} ......${NC}"
        break;;
    * )echo -e "${R} ****** INVALID RESPONSE ******${NC}"
    echo -en '\n';;
    esac
done
else
    echo -e "${BIB}###### [ ${BIY}Up to Date, Skipping${NC}${BIB} ] ######${NC}";
fi
